const fs = require('node:fs')
const path = require('node:path')
const { REST } = require('@discordjs/rest')
const { Routes } = require('discord-api-types/v9')
const { CLIENT, SERVER, TOKEN } = require('./config.js')
const commandsPath = path.join(__dirname, 'commands')
const commands = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js')).map(file => require(path.join(commandsPath, file)).data.toJSON())
new REST({ version: '9' }).setToken(TOKEN).put(Routes.applicationGuildCommands(CLIENT, SERVER), { body: commands }).then(() => console.log('Commands registered')).catch(console.error)